export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
export const FETCH_EXCHANGER = 'FETCH_EXCHANGER';
export const FETCH_EXCHANGER_SUCCESS = 'FETCH_EXCHANGER_SUCCESS';
export const FETCH_EXCHANGER_ERROR = 'FETCH_EXCHANGER_ERROR';
export const SET_AMOUNT = 'SET_AMOUNT';
export const ADD_SELECTED_CURRENCY = 'ADD_SELECTED_CURRENCY';
export const REMOVE_SELECTED_CURRENCY= 'REMOVE_SELECTED_CURRENCY';
